{% set name = "liblzf" %}
{% set version = "3.6" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  - url: http://dist.schmorp.de/{{ name }}/{{ name }}-{{ version }}.tar.gz
    sha256: 9c5de01f7b9ccae40c3f619d26a7abec9986c06c36d260c179cedd04b89fb46a
    patches:
      - 0001-Make-sure-that-the-library-is-linked-with-C-symbols.patch
  - path: CMakeLists.txt
  - path: liblzf-config.cmake.in
  - path: liblzf.pc.in

build:
  number: 3
  run_exports:
    - {{ pin_subpackage('liblzf', max_pin='x.x') }}

requirements:
  build:
    - {{ compiler("c") }}
    - {{ stdlib("c") }}
    - cmake
    - make

test:
  commands:
    - test -f $PREFIX/lib/{{ name }}$SHLIB_EXT  # [unix]
    - test -f $PREFIX/lib/pkgconfig/{{ name }}.pc  # [unix]
    - test -f ${PREFIX}/lib/cmake/{{ name }}/{{ name }}-config.cmake  # [unix]
    - if not exist %PREFIX%\\Library\\bin\\lzf%SHLIB_EXT% exit 1  # [win]
    - if not exist %PREFIX%\\Library\\lib\\lzf.lib exit 1  # [win]
    - if not exist %PREFIX%\\Library\\lib\\pkgconfig\\{{ name }}.pc exit 1  # [win]
    - if not exist %PREFIX%\\Library\\lib\\cmake\\{{ name }}\\{{ name }}-config.cmake exit 1  # [win]

about:
  home: http://oldhome.schmorp.de/marc/liblzf.html
  summary: LZF is an extremely fast (not that much slower than a pure memcpy) compression algorithm.
  license: BSD-2-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - Tobias-Fischer
